server:
  port: 0

spring:
  application:
    name: crypto-service

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka